"""empty message

Revision ID: 53d84f076f84
Revises: None
Create Date: 2016-02-06 01:45:53.960000

"""

# revision identifiers, used by Alembic.
revision = '53d84f076f84'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('marked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    ### end Alembic commands ###
